### ISSUE TITLE
Pex ranking issue

### ISSUE THREAD

**Issue by VQ9** [VolmitSoftware/PermissionsEx#14] opened 2020-02-18 18:18 UTC
I have e,g two ranks
Owner and Emerald
Obviously Owner is ranked higher but when I do /pex group Emerald user add (username) the prefix of Emerald takes precedent over the higher ranked Owner

(My Sql storage)

**Comment by AvianAeternum** [comment] 2020-02-18 18:23
Hey there, this fork of pex is about to be archived, as ZML has returned to the prior repo. This isnt a bug or a code issue.

The issue is your ladder setup, Make sure both ranks have a prefix, and owner is higher on the ladder, by assigning it a value closer to 1, and assigning emerald a value closer to 1000

**Closed as completed by AvianAeternum** 2020-02-18 18:23 UTC

**Comment by VQ9** [comment] 2020-02-18 18:24
It is. That is the problem

**Comment by AvianAeternum** [comment] 2020-02-18 18:25
Send me your permissions.yml
preferably in a pastebin

**Comment by VQ9** [comment] 2020-02-18 18:26
(Mysql)

**Comment by AvianAeternum** [comment] 2020-02-18 18:26
ah shit

**Comment by VQ9** [comment] 2020-02-18 18:26
![image](https://user-images.githubusercontent.com/60553050/74765845-2b0e4800-527c-11ea-9448-6d2a989690d6.png)
![image](https://user-images.githubusercontent.com/60553050/74765871-33668300-527c-11ea-88d5-3715c599b3c9.png)

**Comment by VQ9** [comment] 2020-02-18 18:27
![image](https://user-images.githubusercontent.com/60553050/74765911-45482600-527c-11ea-964c-51358eccf20d.png)

**Comment by VQ9** [comment] 2020-02-18 18:27
idk whats wrong :/

**Comment by AvianAeternum** [comment] 2020-02-18 18:28
I dont believe sql supported prefix and suffix storage, it might think theres two copies of each rank, and the prefix for owner isnt being assigned due to some archaic internal logic, its giving the owner rank that has a ladder, instead of the one that has a prefix?

**Comment by VQ9** [comment] 2020-02-18 18:29
no cause when I remove Emerald I still have the prefix of Owner? idk

**Comment by AvianAeternum** [comment] 2020-02-18 18:32
Set emeralds ranking to 101 real quick, 100 and below are reserved for administrative ranks, and they dont play nicely with the ladder on purpose to prevent abuse

**Comment by VQ9** [comment] 2020-02-18 18:39
that worked!

**Comment by AvianAeternum** [comment] 2020-02-18 18:46
Awesome, Enjoy.
